apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sql-monitor-api
  description: SQL Monitor API
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://red-gate.com
      title: Redgate
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:sql-monitor
  definition:
    $text: https://github.com/asydikov/backstage-sql-monitor/blob/main/sql-monitor-api/swagger.json
